### ISSUE TITLE
Bootstrap not loaded

### ISSUE THREAD

**Issue by Linuus** [ericmj/gaze#3]
Hi!

I just tried to run this and bootstrap is not loaded, making it look like this:

![skarmavbild 2015-10-25 kl 16 15 30](https://cloud.githubusercontent.com/assets/379823/10716294/3bebe746-7b34-11e5-9ad7-aa03c327d875.png)

Did I do something wrong when setting it up? :)

**Comment by ericmj** [comment]
Have you run `bower install`? Also note that this project is just for play, it's not finished or supported.

**Comment by Linuus** [comment]
`bower install` is run as a postinstall hook. I tried running it manually but it didn't make any difference. It looks like brunch just doesn't pick up the css files installed with bower. Shouldn't it pick that up automatically?

Does it work for you?

Yeah, I know it's nothing too serious :) I just thought i looked a bit interesting to check out and learn a few things from. I'm very new to Elixir/Phoenix.

Also, if you don't have time to answer my questions about the project, please feel free to close this issue. I'm just interested to learn :)

**Comment by ericmj** [comment]
I haven't run the project in some time so I don't what works or doesn't work. Sorry.
